#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Marie-Christine Boucher
url: 'localhost:4000'
baseurl: "/mariechristine-boucher-cv" #change it according to your repository name
twitter_username: marie_c_boucher
github_username: mariechristineb
description: Marie-Christine Boucher is a doctoral candidate in German literary and cultural studies at Justus Liebig University Giessen.
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: ceramic # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
#analytics: UA-83979019-1



# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes
remote_theme: orbit

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
